### PR TITLE
More relocations

### PR DESCRIPTION
**Pull request by anvorgesa**
Added the "provided" scope to AdvancedBan, as it is not supposed to be shaded.
And made more relocations.

### CODE REVIEW

**Comment by ExceptedPrism3** [comment]
Appreciate it, will be merged later on this week!

**Review by ExceptedPrism3 — COMMENTED** [review]
Added provided to the advancedban dependency break the plugin's database connection

**Comment by anvorgesa** [comment]
If you send the stacktrace it will be very helpful, AdvancedBan needs to be a provided dependency otherwise this plugin will break every other plugin that properly uses AdvancedBan's API

**Comment by ExceptedPrism3** [comment]
AdvancedBan's plugin doesn't have the best API out there or the support of it.

Here's the error
image

**Pull request merged**
